import {AuthField} from './models/auth-field.model';

export const AuthFieldsRegistry: AuthField[] = [
  {
    name: 'firstName',
    label: 'First Name',
    mode: 'register',
    type: 'text',
    defaultValue: null,
    placeholder: 'John',
    icon: 'create',
    validators: ['required'],
  },
  {
    name: 'lastName',
    label: 'Last Name',
    mode: 'register',
    type: 'text',
    defaultValue: null,
    placeholder: 'Smith',
    icon: 'create',
    validators: ['required'],
  },
  {
    name: 'email',
    label: 'Email',
    mode: 'login',
    type: 'email',
    defaultValue: null,
    placeholder: 'johnsmith@email.com',
    icon: 'email',
    validators: ['required', 'email'],
  },
  {
    name: 'username',
    label: 'Username',
    mode: 'register',
    type: 'text',
    defaultValue: null,
    placeholder: 'johnsmith',
    icon: 'account_box',
    validators: ['required'],
  },
  {
    name: 'password',
    label: 'Password',
    mode: 'login',
    type: 'password',
    defaultValue: null,
    placeholder: '********',
    icon: 'lock',
    validators: ['required'],
  },
  {
    name: 'passwordConfirm',
    label: 'Confirm Password',
    mode: 'register',
    type: 'password',
    defaultValue: null,
    placeholder: '********',
    icon: 'lock',
    validators: ['required'],
  },
];
